# coding: utf-8

require 'yaml'

desc "今までの食事の名前とカロリー履歴ファイルを作成"
  file 'menu_history.yml' => 'daily.yml' do |t|
  sh "type #{t.prerequisites.join(' ')} >> #{t.name}" # Windowsの場合はcatの代わりにtype
end

rule '.yml' => '.log' do |t|
  data = {}
  File.open(t.source).each do |line|
    data.merge!(Hash[*line.chomp!.split(/,/)])
  end

  File.open(t.name, 'w') { |f|
    f.write data.to_yaml
  }
end
